name: Build JATSXML
run-name: Build JATSXML data
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: ls
      - run: chmod +x build/to_jatsxml.sh
      - run: ./build/to_jatsxml.sh
