name: Build JATSXML
run-name: Build JATSXML data
on: [push]
jobs:
  build-jatsxml-publishing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build JATSXML
        run: |
          sudo apt install pandoc
          chmod +x ./build/to_jatsxml.sh
          ./build/to_jatsxml.sh

