name: Build JATSXML
run-name: Build JATSXML data
on: [push]
permissions:
  contents: write
jobs:
  build-jatsxml-publishing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0  # Fetch all branches
      
      - name: Build JATSXML
        run: |
          sudo apt install pandoc
          chmod +x ./build/to_jatsxml.sh
          ./build/to_jatsxml.sh
      
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
      
      - name: Stash built files
        run: |
          git add .
          git stash push -m "Built JATSXML files"
      
      - name: Checkout prod and apply changes
        run: |
          git checkout prod
          git stash pop
          git add .
          git commit -m "Chore: Build JATSXML files" || echo "No changes to commit"
          git push origin prod
